ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER "pingpong" IDENTIFIED BY "pingpong123";

GRANT CONNECT, RESOURCE, CREATE VIEW TO "pingpong";

ALTER USER "pingpong" DEFAULT TABLESPACE "WEB0206"
QUOTA 10M ON "WEB0206";