SELECT * FROM "AUTH_KEY";  -- 인증 키
SELECT * FROM "BOARD" ;  -- 게시글
SELECT * FROM "BOARD_IMG" ; -- 게시글 이미지 
SELECT * FROM "BOOKMARK" ;  -- 북마크(컬렉션)
SELECT * FROM "CAREER" ;  -- 경력
SELECT * FROM "COMMENT" ;   -- 댓글
SELECT * FROM "DECLARATION" ;   -- 신고내용
SELECT * FROM "FOLLOW" ;   -- 팔로우/팔로잉
SELECT * FROM "HASHTAG" ;  -- 해시태그 
SELECT * FROM "HASHTAG_BOARD" ;  -- 해시태그-게시글 연결
SELECT * FROM "INQUIRY" ;  -- 문의
SELECT * FROM "INTERESTS" ;  -- 관심분야
SELECT * FROM "LIKE" ;  -- 게시글 좋아요
SELECT * FROM "MEMBER" ;  -- 회원정보
SELECT * FROM "MEMBER_INTERESTS" ;  -- 회원-관심분야 연결
SELECT * FROM "MEMBER_PROFILE" ;  -- 회원 프로필 정보
SELECT * FROM "MEMBER_SNS" ;  -- 회원-SNS 연결
SELECT * FROM "MEMBER_TECH" ;  -- 회원-기술 연결
SELECT * FROM "MESSAGE" ;  -- 메시지
SELECT * FROM "NOTICE" ;  -- 알람
SELECT * FROM "SEARCHES" ;  -- 검색
SELECT * FROM "SEARCH_HASHTAG" ;  -- 해시태그-검색 연결
SELECT * FROM "SEARCH_MEMBERS";  -- 회원-검색 연결
SELECT * FROM "SNS";  -- SNS
SELECT * FROM "TECH";  -- 기술/지식

UPDATE "COMMENT" SET
		COMMENT_DEL_FL = 'N';
COMMIT;


SELECT COMMENT_NO, COMMENT_CONTENT,
	CASE  
		WHEN SYSDATE - COMMENT_DATE < 1/24/60
		THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24 * 60 * 60 ) || '초 전'
		WHEN SYSDATE - COMMENT_DATE < 1/24
		THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24 * 60) || '분 전'
		WHEN SYSDATE - COMMENT_DATE < 1
		THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24) || '시간 전'
		ELSE TO_CHAR(COMMENT_DATE, 'YYYY-MM-DD')
	END COMMENT_DATE,
 
	BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG, PARENT_NO, COMMENT_DEL_FL,
	(SELECT COUNT(*) FROM "COMMENT" IIC WHERE IIC.PARENT_NO IN (SELECT IC.COMMENT_NO FROM "COMMENT") AND COMMENT_DEL_FL ='N') CHILD_CHECK
FROM "COMMENT" IC
JOIN "MEMBER" M ON(IC.COMMENT_MEMBER_NO = M.MEMBER_NO)
LEFT JOIN "MEMBER_PROFILE" USING(MEMBER_NO)
WHERE COMMENT_NO = 6;


UPDATE "COMMENT" SET
PARENT_NO = 0
WHERE PARENT_NO IS NULL;

SELECT LEVEL, C.* FROM
			(SELECT COMMENT_NO, COMMENT_CONTENT,
				CASE  
					WHEN SYSDATE - COMMENT_DATE < 1/24/60
					THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24 * 60 * 60 ) || '초 전'
					WHEN SYSDATE - COMMENT_DATE < 1/24
					THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24 * 60) || '분 전'
					WHEN SYSDATE - COMMENT_DATE < 1
					THEN FLOOR( (SYSDATE - COMMENT_DATE) * 24) || '시간 전'
					ELSE TO_CHAR(COMMENT_DATE, 'YYYY-MM-DD')
				END COMMENT_DATE,
			 
				BOARD_NO, MEMBER_NO, MEMBER_NICKNAME, PROFILE_IMG, PARENT_NO, COMMENT_DEL_FL,
				(SELECT COUNT(*) FROM "COMMENT" IIC WHERE IIC.PARENT_NO IN (SELECT IC.COMMENT_NO FROM "COMMENT") AND COMMENT_DEL_FL ='N') CHILD_CHECK
			FROM "COMMENT" IC
			JOIN "MEMBER" M ON(IC.COMMENT_MEMBER_NO = M.MEMBER_NO)
			LEFT JOIN "MEMBER_PROFILE" USING(MEMBER_NO)
			WHERE BOARD_NO = 6) C
		WHERE COMMENT_DEL_FL = 'N'
		START WITH PARENT_NO = 0
		CONNECT BY PRIOR COMMENT_NO = PARENT_NO
		ORDER SIBLINGS BY COMMENT_NO;
		
ALTER TABLE "pingpong".BOARD DROP CONSTRAINT SYS_C008273;

SELECT IMG_ADDRESS FROM "BOARD_IMG" WHERE BOARD_NO = 37 AND IMG_ORDER = 1;


DELETE FROM "BOARD" WHERE MEMBER_NO = 1;