SELECT EMP_NAME 사원명, FLOOR(ABS(SYSDATE - HIRE_DATE)) AS 근무일수1, FLOOR( SYSDATE - HIRE_DATE) AS 근무일수2 
FROM EMPLOYEE;

SELECT EMP_ID , EMP_NAME , EMAIL , PHONE 
FROM EMPLOYEE
WHERE MOD(EMP_ID, 2) = 1; 

SELECT *
FROM EMPLOYEE
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12 >=20;

SELECT EMP_NAME ,  SUBSTR(EMP_NO, 0, 8) || '******' 주민등록번호
FROM EMPLOYEE;

SELECT EMP_NAME ,JOB_CODE ,TO_CHAR((SALARY + (SALARY*NVL(BONUS, 0)))*12,'L999,999,999') "연봉(원)"
FROM EMPLOYEE;

SELECT EMP_ID , EMP_NAME , DEPT_CODE , HIRE_DATE 
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D9') AND EXTRACT (YEAR FROM HIRE_DATE) = 2004;

SELECT EMP_NAME , HIRE_DATE , LAST_DAY(HIRE_DATE) - HIRE_DATE + 1 "입사한 달의 근무 일수"
FROM EMPLOYEE;

SELECT EMP_NAME , DEPT_CODE , TO_CHAR(TO_DATE(SUBSTR(EMP_NO, 0, 6), 'RRMMDD'), 'YY"년" MM"월" DD"일"') 생년월일, 
-- FLOOR((SYSDATE - TO_DATE(SUBSTR(EMP_NO, 0, 6), 'RRMMDD'))/365)  "만 나이", 윤년을 생각하지 못함
trunc(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 0, 6), 'RRMMDD'))/12) "만 나이"
FROM EMPLOYEE;