-- 1. -------------------------------------------------------------------------
SELECT STUDENT_NAME "학생 이름" , STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 2. -------------------------------------------------------------------------
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY TO_DATE(19||SUBSTR(STUDENT_SSN,1,6), 'RRRRMMDD') DESC;

-- 3. -------------------------------------------------------------------------
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소" 
FROM TB_STUDENT
WHERE ENTRANCE_DATE BETWEEN '1900/01/01' AND '1999/12/31'
AND (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
ORDER BY STUDENT_NAME ;

-- 4. -------------------------------------------------------------------------
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6), 'RRRRMMDD');

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '법학과')
ORDER BY TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6), 'RRRRMMDD');

-- 5. -------------------------------------------------------------------------
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO ='C3118100'
ORDER BY POINT DESC, STUDENT_NO ;

-- 6. -------------------------------------------------------------------------
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

-- 7. -------------------------------------------------------------------------
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- 8. -------------------------------------------------------------------------
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

-- 9. -------------------------------------------------------------------------
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS TC, TB_CLASS_PROFESSOR TCP, TB_PROFESSOR TP, TB_DEPARTMENT TD
WHERE TC.CLASS_NO = TCP.CLASS_NO AND TCP.PROFESSOR_NO = TP.PROFESSOR_NO AND TD.DEPARTMENT_NO = TP.DEPARTMENT_NO AND CATEGORY = '인문사회';

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_DEPARTMENT
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
WHERE CATEGORY = '인문사회';

-- 10. -------------------------------------------------------------------------
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", (SELECT ROUND(AVG(POINT),1)
													FROM TB_STUDENT
													JOIN TB_GRADE USING(STUDENT_NO)
													WHERE STUDENT_NO = MAIN.STUDENT_NO) "전체 평점"
FROM TB_STUDENT MAIN
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
ORDER BY STUDENT_NO;

-- 11. -------------------------------------------------------------------------
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 12. -------------------------------------------------------------------------
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND SUBSTR(TERM_NO,1,4) ='2007'
ORDER BY 1;

-- 13. -------------------------------------------------------------------------
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE PROFESSOR_NO IS NULL AND CATEGORY = '예체능';


-- 14. -------------------------------------------------------------------------
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 15. -------------------------------------------------------------------------
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME , DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;

-- 16. -------------------------------------------------------------------------
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT), 8)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE = '전공선택'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 17. -------------------------------------------------------------------------
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

-- 18. -------------------------------------------------------------------------
SELECT STUDENT_NO, STUDENT_NAME
FROM(
	SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) 평균
	FROM TB_STUDENT
	JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
	JOIN TB_GRADE USING(STUDENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO, STUDENT_NAME
	ORDER BY 평균 DESC)
WHERE ROWNUM = 1;

-- 19. -------------------------------------------------------------------------
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1) 
FROM TB_GRADE 
LEFT JOIN TB_STUDENT USING(STUDENT_NO) 
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_CLASS USING(CLASS_NO) 
WHERE CATEGORY = '자연과학' 
AND CLASS_TYPE LIKE '전공%' 
GROUP BY DEPARTMENT_NAME ORDER BY 1;






